
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("﻿GO:0016032", "viral process");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0000165", "MAPK cascade");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0045944", "positive regulation of transcription by RNA polymerase II");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0002479", "antigen processing and presentation of exogenous peptide antigen via MHC class I, TAP-dependent");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0043488", "regulation of mRNA stability");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0070498", "interleukin-1-mediated signaling pathway");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006521", "regulation of cellular amino acid metabolic process");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0038061", "NIK/NF-kappaB signaling");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:1902036", "regulation of hematopoietic stem cell differentiation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006468", "protein phosphorylation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0033209", "tumor necrosis factor-mediated signaling pathway");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0015031", "protein transport");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0002223", "stimulatory C-type lectin receptor signaling pathway");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0045893", "positive regulation of transcription, DNA-templated");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006367", "transcription initiation from RNA polymerase II promoter");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0010972", "negative regulation of G2/M transition of mitotic cell cycle");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0000398", "mRNA splicing, via spliceosome");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0016579", "protein deubiquitination");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0038095", "Fc-epsilon receptor signaling pathway");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0000209", "protein polyubiquitination");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006888", "endoplasmic reticulum to Golgi vesicle-mediated transport");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006915", "apoptotic process");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006120", "mitochondrial electron transport, NADH to ubiquinone");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0050852", "T cell receptor signaling pathway");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0051092", "positive regulation of NF-kappaB transcription factor activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0061418", "regulation of transcription from RNA polymerase II promoter in response to hypoxia");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:1901990", "regulation of mitotic cell cycle phase transition");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0030036", "actin cytoskeleton organization");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0045071", "negative regulation of viral genome replication");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0010629", "negative regulation of gene expression");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0007165", "signal transduction");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0031145", "anaphase-promoting complex-dependent catabolic process");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0007049", "cell cycle");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006470", "protein dephosphorylation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0043065", "positive regulation of apoptotic process");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006357", "regulation of transcription by RNA polymerase II");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0031146", "SCF-dependent proteasomal ubiquitin-dependent protein catabolic process");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0050821", "protein stabilization");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0000122", "negative regulation of transcription by RNA polymerase II");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0060071", "Wnt signaling pathway, planar cell polarity pathway");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0051607", "defense response to virus");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0043123", "positive regulation of I-kappaB kinase/NF-kappaB signaling");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006486", "protein glycosylation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0032760", "positive regulation of tumor necrosis factor production");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0046777", "protein autophosphorylation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0042795", "snRNA transcription by RNA polymerase II");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0055085", "transmembrane transport");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0032981", "mitochondrial respiratory chain complex I assembly");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0035556", "intracellular signal transduction");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0016567", "protein ubiquitination");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0010628", "positive regulation of gene expression");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0070125", "mitochondrial translational elongation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0050727", "regulation of inflammatory response");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0032755", "positive regulation of interleukin-6 production");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0045892", "negative regulation of transcription, DNA-templated");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006886", "intracellular protein transport");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0070126", "mitochondrial translational termination");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006364", "rRNA processing");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0050790", "regulation of catalytic activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006974", "cellular response to DNA damage stimulus");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0010803", "regulation of tumor necrosis factor-mediated signaling pathway");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0072659", "protein localization to plasma membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0043547", "positive regulation of GTPase activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0010499", "proteasomal ubiquitin-independent protein catabolic process");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006469", "negative regulation of protein kinase activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0043161", "proteasome-mediated ubiquitin-dependent protein catabolic process");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0008630", "intrinsic apoptotic signaling pathway in response to DNA damage");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0071222", "cellular response to lipopolysaccharide");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0018105", "peptidyl-serine phosphorylation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0008283", "cell population proliferation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0035335", "peptidyl-tyrosine dephosphorylation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0008380", "RNA splicing");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0045087", "innate immune response");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0008284", "positive regulation of cell population proliferation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0051301", "cell division");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0030334", "regulation of cell migration");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0042407", "cristae formation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:1900034", "regulation of cellular response to heat");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006954", "inflammatory response");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006303", "double-strand break repair via nonhomologous end joining");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0032757", "positive regulation of interleukin-8 production");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0000381", "regulation of alternative mRNA splicing, via spliceosome");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0090263", "positive regulation of canonical Wnt signaling pathway");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006914", "autophagy");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0008285", "negative regulation of cell population proliferation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0043312", "neutrophil degranulation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0030433", "ubiquitin-dependent ERAD pathway");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0042254", "ribosome biogenesis");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0032481", "positive regulation of type I interferon production");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0042127", "regulation of cell population proliferation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0043044", "ATP-dependent chromatin remodeling");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0048013", "ephrin receptor signaling pathway");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0016197", "endosomal transport");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0016070", "RNA metabolic process");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0007040", "lysosome organization");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0016192", "vesicle-mediated transport");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0018345", "protein palmitoylation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0032092", "positive regulation of protein binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006511", "ubiquitin-dependent protein catabolic process");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006338", "chromatin remodeling");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0050911", "detection of chemical stimulus involved in sensory perception of smell");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006614", "SRP-dependent cotranslational protein targeting to membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0019083", "viral transcription");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006413", "translational initiation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0000184", "nuclear-transcribed mRNA catabolic process, nonsense-mediated decay");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0007186", "G protein-coupled receptor signaling pathway");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0002181", "cytoplasmic translation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006412", "translation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0007608", "sensory perception of smell");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0061640", "cytoskeleton-dependent cytokinesis");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0002323", "natural killer cell activation involved in immune response");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005654", "nucleoplasm");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005829", "cytosol");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005634", "nucleus");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005737", "cytoplasm");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005739", "mitochondrion");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0016020", "membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005743", "mitochondrial inner membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005794", "Golgi apparatus");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005730", "nucleolus");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0032991", "protein-containing complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0000139", "Golgi membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005759", "mitochondrial matrix");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005765", "lysosomal membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005813", "centrosome");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005789", "endoplasmic reticulum membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0000502", "proteasome complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0043231", "intracellular membrane-bounded organelle");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0031965", "nuclear membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0070062", "extracellular exosome");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005886", "plasma membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005856", "cytoskeleton");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0016607", "nuclear speck");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005747", "mitochondrial respiratory chain complex I");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0010008", "endosome membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005874", "microtubule");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0048471", "perinuclear region of cytoplasm");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005635", "nuclear envelope");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005938", "cell cortex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0016604", "nuclear body");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0036064", "ciliary basal body");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0015629", "actin cytoskeleton");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005783", "endoplasmic reticulum");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0043005", "neuron projection");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0045121", "membrane raft");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005839", "proteasome core complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0016324", "apical plasma membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005764", "lysosome");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0071013", "catalytic step 2 spliceosome");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005753", "mitochondrial proton-transporting ATP synthase complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005758", "mitochondrial intermembrane space");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:1904115", "axon cytoplasm");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0000781", "chromosome, telomeric region");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0045111", "intermediate filament cytoskeleton");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0022624", "proteasome accessory complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0035861", "site of double-strand break");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0031902", "late endosome membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005681", "spliceosomal complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0030176", "integral component of endoplasmic reticulum membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005923", "bicellular tight junction");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0016592", "mediator complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0042645", "mitochondrial nucleoid");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0008021", "synaptic vesicle");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0098978", "glutamatergic synapse");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0030496", "midbody");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0101031", "chaperone complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0030054", "cell junction");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0043296", "apical junction complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0030027", "lamellipodium");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005793", "endoplasmic reticulum-Golgi intermediate compartment");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0030173", "integral component of Golgi membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0016328", "lateral plasma membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005694", "chromosome");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0035577", "azurophil granule membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005762", "mitochondrial large ribosomal subunit");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0043025", "neuronal cell body");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0009898", "cytoplasmic side of plasma membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0012507", "ER to Golgi transport vesicle membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0000151", "ubiquitin ligase complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005779", "integral component of peroxisomal membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0030018", "Z disc");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0032588", "trans-Golgi network membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0000786", "nucleosome");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005912", "adherens junction");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0032040", "small-subunit processome");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0055038", "recycling endosome membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0022625", "cytosolic large ribosomal subunit");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0022627", "cytosolic small ribosomal subunit");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0031105", "septin complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005940", "septin ring");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0032153", "cell division site");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0042788", "polysomal ribosome");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005515", "protein binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("51596", "");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0003723", "RNA binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0046872", "metal ion binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005524", "ATP binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0019901", "protein kinase binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0042802", "identical protein binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0004674", "protein serine/threonine kinase activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0106310", "protein serine kinase activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0106311", "protein threonine kinase activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0031625", "ubiquitin protein ligase binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0003677", "DNA binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0003713", "transcription coactivator activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0008134", "transcription factor binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0030674", "protein-macromolecule adaptor activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0008137", "NADH dehydrogenase (ubiquinone) activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0051087", "chaperone binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0106307", "protein threonine phosphatase activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0106306", "protein serine phosphatase activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0019899", "enzyme binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0003779", "actin binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0019903", "protein phosphatase binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0004842", "ubiquitin-protein transferase activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005085", "guanyl-nucleotide exchange factor activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0008270", "zinc ion binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0003724", "RNA helicase activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0042803", "protein homodimerization activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0043130", "ubiquitin binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0044877", "protein-containing complex binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0031267", "small GTPase binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0051015", "actin filament binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0003725", "double-stranded RNA binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0000993", "RNA polymerase II complex binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005525", "GTP binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0019904", "protein domain specific binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0004672", "protein kinase activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0004984", "olfactory receptor activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0004930", "G protein-coupled receptor activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005549", "odorant binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0003735", "structural constituent of ribosome");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0016032", "viral process");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0043687", "post-translational protein modification");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006783", "heme biosynthetic process");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006457", "protein folding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006355", "regulation of transcription, DNA-templated");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006626", "protein targeting to mitochondrion");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006325", "chromatin organization");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0016236", "macroautophagy");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0065003", "protein-containing complex assembly");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0007030", "Golgi organization");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0000086", "G2/M transition of mitotic cell cycle");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0090090", "negative regulation of canonical Wnt signaling pathway");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0018215", "protein phosphopantetheinylation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0061025", "membrane fusion");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0009615", "response to virus");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:1900244", "positive regulation of synaptic vesicle endocytosis");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:1990668", "vesicle fusion with endoplasmic reticulum-Golgi intermediate compartment (ERGIC) membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006892", "post-Golgi vesicle-mediated transport");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0031175", "neuron projection development");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0036258", "multivesicular body assembly");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0035646", "endosome to melanosome transport");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0050920", "regulation of chemotaxis");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0031468", "nuclear envelope reassembly");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0045652", "regulation of megakaryocyte differentiation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0000045", "autophagosome assembly");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0046426", "negative regulation of receptor signaling pathway via JAK-STAT");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0045540", "regulation of cholesterol biosynthetic process");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0006890", "retrograde vesicle-mediated transport, Golgi to endoplasmic reticulum");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0010506", "regulation of autophagy");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0034620", "cellular response to unfolded protein");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0043122", "regulation of I-kappaB kinase/NF-kappaB signaling");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0007098", "centrosome cycle");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0031665", "negative regulation of lipopolysaccharide-mediated signaling pathway");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0032511", "late endosome to vacuole transport via multivesicular body sorting pathway");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0031424", "keratinization");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0007268", "chemical synaptic transmission");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0070268", "cornification");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0050877", "nervous system process");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0030449", "regulation of complement activation");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0042391", "regulation of membrane potential");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:1904813", "ficolin-1-rich granule lumen");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0042470", "melanosome");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0033116", "endoplasmic reticulum-Golgi intermediate compartment membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005925", "focal adhesion");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005802", "trans-Golgi network");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0019774", "proteasome core complex, beta-subunit complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005768", "endosome");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0000159", "protein phosphatase type 2A complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0012505", "endomembrane system");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005667", "transcription regulator complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0042824", "MHC class I peptide loading complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005814", "centriole");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0016605", "PML body");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0030670", "phagocytic vesicle membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005801", "cis-Golgi network");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0030133", "transport vesicle");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005815", "microtubule organizing center");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0071339", "MLL1 complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005833", "hemoglobin complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0044322", "endoplasmic reticulum quality control compartment");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0015630", "microtubule cytoskeleton");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005746", "mitochondrial respirasome");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0000138", "Golgi trans cisterna");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0090575", "RNA polymerase II transcription regulator complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0071144", "heteromeric SMAD protein complex");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0034774", "secretory granule lumen");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005615", "extracellular space");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0045095", "keratin filament");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005887", "integral component of plasma membrane");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005576", "extracellular region");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0031012", "extracellular matrix");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0045296", "cadherin binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0031593", "polyubiquitin modification-dependent protein binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005096", "GTPase activator activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0019900", "kinase binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0004298", "threonine-type endopeptidase activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0048156", "tau protein binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0003714", "transcription corepressor activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0003684", "damaged DNA binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0008022", "protein C-terminus binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0051787", "misfolded protein binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0046982", "protein heterodimerization activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0015035", "protein disulfide oxidoreductase activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0019888", "protein phosphatase regulator activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0003729", "mRNA binding");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0030594", "neurotransmitter receptor activity");
INSERT INTO Gene_Ontology (go_id, go_term) VALUES ("GO:0005245", "voltage-gated calcium channel activity");